- name: install apache2 package and php
  tags: apache,apache2,ubuntu
  package:
    name:
      - apache2
      - libapache2-mod-php
    state: latest
    update_cache: yes
  when: ansible_distribution in "Ubuntu"

- name: copy default html file
  tags: apache,apache2
  copy:
    src: default_site.html
    dest: /var/www/html/index.html
    owner: root
    group: root
    mode: 0644
